= Installation

== Software Requirements

Install the following software:

* https://git-scm.com/[Git]
* https://www.python.org/downloads/[Python 3]
** Avoid using the Windows Store version
** During the installation, don't forget to have Python added to environment variables
** Also make sure that pip is selected as optional feature
* https://code.visualstudio.com/[Visual Studio Code]
** Windows users: during the installation, have it install the explorer context menu additions
** Install the VSCode Markdown Preview Mermaid extension

== Checking Your Python Installation

It's important to check that your Python installation works.
This can be slightly tricky, since the details depend on your OS.
There are two kinds of problems that can arise:

* Python cannot be found
* The wrong version of Python is found

Below are instructions that verify both at the same type.
The goal is that you get Python to tell you which version it is, and that this version is 3.6 or higher.
If you encounter problems, inform a lecturer.

[IMPORTANT]
====
A `$` in the beginning of a line means that you should input that line in a shell.
**Do not write the `$` itself though, only what follows**. For example, `$ ls` means you should enter `ls`.
====

.Windows Instructions
[%collapsible]
====
[note]
=====
In a shell, write

[source,bash]
----
$ python --version
----

If this gives you trouble, try instead

[source,bash]
----
$ py --version
----
=====
====

.MacOS Instructions
[%collapsible]
====
[note]
=====
In the terminal, write

[source,bash]
----
$ python --version
----

If this doesn't work or prints out the wrong version, try

[source,bash]
----
$ python3 --version
----
=====
====

.Linux Instructions
[%collapsible]
====
[note]
=====
In the shell, write

[source,bash]
----
$ python --version
----

If this doesn't work or prints out the wrong version, try

[source,bash]
----
$ python3 --version
----
=====
====

== Checking Your Pip Installation

Pip is Python's package manager: it allows you to easily install now components.
Check if it works by trying out the commands below:

[source,bash]
----
$ pip --version

$ pip3 --version
----

One of these should work and should output something mentioning Python 3.
If pip is not recognized, you will have to https://pip.pypa.io/en/stable/installing/[look up] how to install it.

== Course Related Material

Open a terminal in a directory where you wish to store your course-related files.
Let's first install the testing framework:

[source,bash]
----
$ pip install git+https://github.com/ucll-scripting/testing-framework.git
----

Test the installation of the scripting package by executing the following command.
It should show the output below (or something similar to it, as long as it's not an error message.)

[source,bash]
----
$ scripting
usage: scripting [-h] {version,test} ...

positional arguments:
  {version,test}  sub-command help
    version       returns version
    test          runs tests in all subdirectories

optional arguments:
  -h, --help      show this help message and exit
----

Next, you need to get access to the course material.
The simplest way is cloning, but you can also choose to create your own fork.
This allows you to save your work on GitHub, so that you're sure never to lose any of it.

.Cloning
[%collapsible]
====
[note]
=====
In a shell, write

[source,bash]
----
$ git clone https://github.com/ucll-scripting/exercises.git
----
=====
====

.Forking
[%collapsible]
====
[note]
=====
* Go to https://github.com/ucll-scripting/exercises.git[the repository's website].
* Create a fork (button top right).
* You have now created a copy of the repo under your own account. The URL should look like `https://github.com/<your GitHub name>/exercises.git`.
* Clone your fork
+
[source,bash]
----
$ git clone https://github.com/<your GitHub name>/exercises.git scripting-exercises
----
* Enter the repository's directory
+
[source,bash]
----
$ cd scripting-exercises
----
* Link it to the original repository.
+
[source,bash]
----
$ git remote add upstream https://github.com/ucll-scripting/exercises.git
----

Now you can save your work using

[source,bash]
----
$ git add <file>
$ git commit -m "some message"
$ git push
----

Concrete example:

[source,bash]
----
$ cd 01-basic-python/01-arithmetic/01-five/
$ git add student.py
$ git commit -m "finished 01-five"
$ git push
----
=====
====
